name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Run unit tests
        run: cargo test
      - name: Run linter
        run: cargo clippy
      - name: Run format check
        run: cargo fmt --check
